### ISSUE TITLE
[Feature] Include accessibility tips in Steps 1 and 2

### ISSUE THREAD

**Issue by meowius** [skills/communicate-using-markdown#10]
**Is your feature request related to a problem? Please describe.**

Not a problem, but there are a couple of openings in the ["Communicate using Markdown" lesson](https://github.com/skills/communicate-using-markdown) to add basic accessibility guidance. 🔍

**Describe the solution you'd like**

- "Step 1: Add headers" could include mention of [heading ranks](https://www.w3.org/WAI/tutorials/page-structure/headings/)
- "Step 2: Add an image" could include a tip on how to write alt text. For example, "Describe the information you chose this image to convey" or "Describe the meaning of the image in 100 characters or less."

**Describe alternatives you've considered**

- If appropriate, link to W3C WCAG documentation; the [W3C Images Tutorial](https://www.w3.org/WAI/tutorials/images/) is comprehensive, clear, and from the source
- Consider creating (or encouraging community creation of) a GitHub Skills course covering basics of accessibility for text/image authoring in the GitHub context, such as meaningful headers, link text, alt text for screenshots, and similar

**Additional context**

Nested headers and informative alt text are essential for inclusive access for users with disabilities. 

Learning to implement these consistently is a great skill for folks learning Markdown. _And_ learning them at the beginning can help build good habits and save on rework later! 🎉

**Comment by Warmdriver** [comment]
I encourage the Github starters to  preview the  
 GitHub Skills course covering basics of accessibility for text/image authoring in the GitHub context, such as meaningful headers, link text, alt text for screenshots, and similar 
Additional context

Nested headers and informative alt text are essential for inclusive access for users with disabilities.

Learning to implement these consistently is a great skill for folks learning Markdown. And learning them at the beginning can help build good habits and save on rework later! 🎉

**Comment by meowius** [comment]
> I encourage the Github starters to preview the
GitHub Skills course covering basics of accessibility

Thanks @Warmdriver just making sure I follow — is there already a GitHub Skills course on Accessibility basics? If so, I am having trouble finding it — let me know if you have a link to share! Thank you so much! 👍

**Comment by Warmdriver** [comment]
https://github.com/skills.com

**Comment by Warmdriver** [comment]
Sorry here is the link:
https://github.com/skills

**Comment by meowius** [comment]
Thanks @Warmdriver!
