### ISSUE TITLE
[Bug] Step 0 fails, Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by g-vernon** [skills/communicate-using-markdown#21]
**Describe the bug**
Step 0 initial commit fails with exit code 129, with warning "Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2". This means further sections do not automatically open after tasks are completed.

**To Reproduce**
1. Fork repo
2. Step 0 fails with exit code 129
3. Complete section 1 tasks
4. Wait 20 seconds and refresh README.md
5. Section 2 does not automatically open

**Expected behavior**
1. Fork repo
2. Step 0 completes with no error
3. Complete section 1 tasks
4. Wait 20 seconds and refresh README.md
5. Section 2 automatically opens

**Screenshots**
![Screenshot](https://i.imgur.com/T1gxQNs.png)

**Device information**
 - Type: [Laptop]
 - OS: [Ubuntu 20.04.5 Budgie]
 - Browser [Hardened Firefox]
 - Version [Browser version 107.0]

**Additional context**

**Comment by rsese** [comment]
Thanks for the report!  If you or anyone is interested in opening a PR def. feel free (would be basically the same as https://github.com/skills/continuous-integration/pull/19)!  Otherwise I'll update this week...
