### ISSUE TITLE
[Bug]The link for the tutorial is linked to a forked repo from @morganersery1

### ISSUE THREAD

**Issue by wangyuchen333** [skills/communicate-using-markdown#236]
### Summary

The link for the tutorial is linked to a forked repo from @morganersery1

### How to reproduce

I am not sure if it is designed to be this way. Seems not official.

Please include screenshots.

**Comment by nguyenalex836** [comment]
@wangyuchen333 Hello! This appears to be a duplicate of https://github.com/skills/introduction-to-github/issues/929 - I'll go ahead and close this issue 💛
