### ISSUE TITLE
[Bug] 0-start workflow ends with error 129

### ISSUE THREAD

**Issue by timholy** [skills/communicate-using-markdown#35]
**Describe the bug**
Even after working around the GitHub Actions issue #29, the workflow ends with error code 129.

**To Reproduce**
1. Clone from the template
2. Note that no PR has been submitted even after waiting and refreshing (this is #29)
3. Go to Settings -> Actions -> General, click "Allow GitHub Actions to create and approve pull requests" followed by "Save"
4. Delete the `start markdown` branch
5. Re-run the failing action, "Initial commit". Note it ends in failure.

**Expected behavior**
I expect the action to pass.

**Screenshots**
This is the relevant portion of the log:
```
Switched to branch 'start-markdown'
Your branch is up to date with 'origin/start-markdown'.
usage: git cherry-pick [--edit] [-n] [-m <parent-number>] [-s] [-x] [--ff]
                       [-S[<keyid>]] <commit>...
   or: git cherry-pick (--continue | --skip | --abort | --quit)

    --quit                end revert or cherry-pick sequence
    --continue            resume revert or cherry-pick sequence
    --abort               cancel revert or cherry-pick sequence
    --skip                skip current commit and continue
    --cleanup <mode>      how to strip spaces and #comments from message
    -n, --no-commit       don't automatically commit
    -e, --edit            edit the commit message
    -s, --signoff         add a Signed-off-by trailer
    -m, --mainline <parent-number>
                          select mainline parent
    --rerere-autoupdate   update the index with reused conflict resolution if possible
    --strategy <strategy>
                          merge strategy
    -X, --strategy-option <option>
                          option for merge strategy
    -S, --gpg-sign[=<key-id>]
                          GPG sign commit
    -x                    append commit name
    --ff                  allow fast-forward
    --allow-empty         preserve initially empty commits
    --allow-empty-message
                          allow commits with empty messages
    --keep-redundant-commits
                          keep redundant, empty commits

Error: Process completed with exit code 129.
```

**Device information**
 - Type: GitHub web interface
 - OS: Windows 11
 - Firefox
 - 109.0

**Additional context**
This may be minor, but it's a potential obstacle for new learners.

**Comment by sinsukehlab** [comment]
This error occurred probably because the BASE_BRANCH_NAME env is not set in the previous version (v1.2.0) of skills/action-update-step.
Now that v1.2.1 is released, the error is probably fixed.

**Comment by heiskr** [comment]
Thank you for opening this issue. I believe the underlying problem has been resolved. Please let us know if you continue to experience errors in this course.
