### ISSUE TITLE
[Bug] Error editing empty file

### ISSUE THREAD

**Issue by timholy** [skills/communicate-using-markdown#36]
**Describe the bug**
After successfully working around #29 (via steps described in #35), following the instructions to edit `index.md` generates "Error: Looks like something went wrong!".

**To Reproduce**
1. Take the steps described in #35, if needed
2. Click on 'Pull requests' -> `Start learning markdown`
3. Click `Files changed`. Note that `index.md` is described as "Empty file"
4. Follow the [instructions](https://github.com/skills/communicate-using-markdown#keyboard-activity-edit-your-file-with-headers) and click `...` followed by `Edit file`
5. See the screen that reports "Error: Looks like something went wrong!"

**Expected behavior**
I expected to be able to add text to the file as described in the [instructions](https://github.com/skills/communicate-using-markdown#step-1-add-headers) (Step 1, activity stage 5&6)

**Screenshots**
![image](https://user-images.githubusercontent.com/1525481/214040208-54071e5b-ef75-43a3-af4c-4bb0556f7fd9.png)

**Device information**
 - Type: GitHub web interface via laptop
 - OS: Windows 11
 - Firefox
 - Version 109.0

**Comment by heiskr** [comment]
Thank you for opening this issue. This looks like a GitHub platform 500, which is usually a temporary problem. I'll go ahead and close this issue, but please let us know if you continue to experience errors with this course.
