### ISSUE TITLE
[Bug] Can’t edit file from the three dotted menu

### ISSUE THREAD

**Issue by heidihelen** [skills/communicate-using-markdown#45]
**Describe the bug**
In [Step 1](https://github.com/skills/communicate-using-markdown#step-1-add-headers) “Activity: Edit your file with headers”, step 5, says ”Select Edit file from the three dotted ... menu in the upper right corner of the file view on index.md.” However, when I try to do so `index.md` says `Empty file` and `Edit file` is greyed out. I am stuck on this step.

**To Reproduce**
1. Follow the steps from the [communicate-using-markdown](https://github.com/skills/communicate-using-markdown) repo to create a new repository.
3. Begin the [Step 1](https://github.com/skills/communicate-using-markdown#step-1-add-headers) activity and click `New pull request` in the new repo, comparing `base: main` and `compare: start-markdown`.
4. Observe that steps 4 and 5 don’t allow you to edit `index.md` which is empty.

**Expected behavior**
You can edit `index.md`. I believe it is supposed to create content in that file but it isn’t working.

**Screenshots**
<img width="761" alt="Empty File" src="https://user-images.githubusercontent.com/42740566/220282152-6e3c8ead-3ad5-4262-b632-2b65bb099532.png">

**Device information**
 - Type: MacBook Pro
 - OS: macOS
 - Browser: Chrome
 - Version: 110.0.5481.100

**Additional context**
N/A.

**Comment by selvitica** [comment]
@heidihelen ,
Could you please check if your pull request step was done ?
![image](https://user-images.githubusercontent.com/123870429/220374756-beed8e7f-93af-4afd-93c5-93ede331d41b.png)

**Comment by sinsukehlab** [comment]
You should completely create the PR.
I have opened a PR #44 to clarify the step.

**Comment by heidihelen** [comment]
@selvitica @sinsukehlab Thanks! I thought submitting the PR came later and that the steps were asking to edit the file before the PR was created. The instructions didn’t say to click the “Create pull request” button after changing the branches to compare. Adding info to clarify that step will definitely help. 😁

After submitting my PR, `index.md` is still empty. And the instructions say to “add a #, followed by a space, **before the content** to make it an H1 Header”, but there is no content.

**Comment by heidihelen** [comment]
I’ve since completed this exercise adding my own content to the `index.md` file. It wasn’t clear if we were editing existing content or creating it from scratch.

**Comment by sinsukehlab** [comment]
I have also thought that way at first. "Click **Create pull request**" must be asked.
Creating `index.md` from scratch (an empty file) feels natural to me, but I will emphasize that it is empty.

**Comment by heidihelen** [comment]
@sinsukehlab I wasn’t sure if a GitHub Action would create `index.md` with content that we were editing to give headings or if we were adding brand new content to it. If that could be emphasized, it would be helpful.

As the instructions does say to add a `#` “**before the content** to make it an H1 Header.” I thought it was a bug that `index.md` was created without content.

**Comment by sinsukehlab** [comment]
GitHub Actions workflows can create a file with content, but this course seems to let learners create the content using Markdown.
The "content" in the instruction means the content you like to make it a header.

**Comment by heidihelen** [comment]
@sinsukehlab Thanks for your explanation. Perhaps the line about content could be rewritten to say “any content you like” or the user could copy and paste something like below:

```
H1 - This is an example H1. Add a # before it with a space.
H2 - This is an example H2. Add ## before it with a space.
H3 - This is an example H3. Add ### before it with a space.
H4 - This is an example H4. Add #### before it with a space.
H5 - This is an example H5. Add ##### before it with a space.
H6 - This is an example H6. Add ###### before it with a space.
```
