### ISSUE TITLE
step 3 wont load up after if completed step 2 [Bug]

### ISSUE THREAD

**Issue by ChardPeter** [skills/communicate-using-markdown#84]
### Summary

A clear and concise description of what the bug is, and what you expected to happen.

### How to reproduce

2. Click on '...'
3. Scroll down to '...'

Please include screenshots.

**Comment by Moonshieldgru** [comment]
> ### Summary
> A clear and concise description of what the bug is, and what you expected to happen.
> 
> ### How to reproduce
> 1. Go to '...'
> 2. Click on '...'
> 3. Scroll down to '...'
> 4. See error
> 
> Please include screenshots.
> 
> ### Additional context
> Add any other context about the problem here.
